# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-yaml
          - id: trailing-whitespace
          - id: end-of-file-fixer
    # - repo: local
    #   hooks:
    #       - id: pylint
    #         name: pylint
    #         entry: pylint
    #         language: system
    #         types: [python]
    #         require_serial: true
    - repo: https://github.com/psf/black
      rev: 23.1.0
      hooks:
          - id: black
